### ISSUE TITLE
[Android] Game gets stuck at the loading screen.

### ISSUE THREAD

**Issue by ICoolBuddy** [shishkabob27/CardWarsKingdom#14]
When opening the game, it plays the "Made with Unity" and the Cartoon Network intro and when it gets to the loading screen it gets stuck. I've waited for about 10 minutes and still nothing happens. I tested it on Android 14 & Android 10. It's still the same.

![Screenshot_20240101_133422_Card Wars Kingdom](https://github.com/shishkabob27/CardWarsKingdom/assets/81433896/ac10e8c2-acd5-4ac8-8cfb-3749b5581bf3)

**Comment by Sabersabersaber123** [comment]
same here, still have this problem
