### ISSUE TITLE
when evolving/upgrading characters theres no exit button so im forced to restart the gamae every time i wanna upgrade,

### ISSUE THREAD

**Issue by Sabersabersaber123** [shishkabob27/CardWarsKingdom#4]
the hand points to an exit button that is not there.

**Comment by MaltMatcha** [comment]
Also having this issue, the exit button does not appear and therefore you are unable to upgrade cards without restarting the game every time.

**Comment by Randomplayer382647** [comment]
Close the issue it was fixed
